var angka = prompt('masukan angka');

switch (angka) {
    case '1':
        alert('angka yang anda masukan adalah 1')
        break;
    case '2':
        alert('angka yang anda masukan adalah 2')
        break;
    case '3':
        alert('angka yang anda masukan adalah 3')
        break;
    case '4':
        alert('angka yang anda masukan adalah 4')
        break;
    case '5':
        alert('angka yang anda masukan adalah 5')
        break;
    case '6':
        alert('angka yang anda masukan adalah 6')
        break;
    case '7':
        alert('angka yang anda masukan adalah 7')
        break;
    case '8':
        alert('angka yang anda masukan adalah 8')
        break;
    default:
        alert('angka yang anda masukan tidak terdaftar')
        break;
}


// var angka = parseInt(prompt('masukan angka'));

// switch (angka) {
//     case 1:
//         alert('angka yang anda masukan adalah 1')
//         break;
//     case 2:
//         alert('angka yang anda masukan adalah 2')
//         break;
//     default:
//         alert('angka yang anda masukan tidak terdaftar')
//         break;
// }